"""eeee

Revision ID: 07a339e166b7
Revises: 921e99468c58
Create Date: 2021-08-08 22:25:13.945188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07a339e166b7'
down_revision = '921e99468c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'limit_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
