"""タスク名のカラムをtitleに変更

Revision ID: 64de43dc85ad
Revises: 07a339e166b7
Create Date: 2021-10-22 00:29:41.547605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64de43dc85ad'
down_revision = '07a339e166b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_tasks', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('sub_tasks', 'sub_task')
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('tasks', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('tasks', 'title')
    op.add_column('sub_tasks', sa.Column('sub_task', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('sub_tasks', 'title')
    # ### end Alembic commands ###
