"""[fix] username unique

Revision ID: 720af62d9d7a
Revises: 3d7966086c03
Create Date: 2021-07-24 17:59:46.681136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720af62d9d7a'
down_revision = '3d7966086c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
