"""String型に変更

Revision ID: 87581366d7a9
Revises: bc123abcfaa7
Create Date: 2021-08-08 22:20:29.868097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87581366d7a9'
down_revision = 'bc123abcfaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'limit_at',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'limit_at',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
