"""[add] sorted_id at task

Revision ID: 905c9fb37cdd
Revises: e497ecc26d17
Create Date: 2021-12-26 16:26:21.658698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '905c9fb37cdd'
down_revision = 'e497ecc26d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sorted_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sorted_id')
    # ### end Alembic commands ###
