"""iii

Revision ID: 921e99468c58
Revises: c5058bc4988a
Create Date: 2021-08-08 22:24:52.939718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921e99468c58'
down_revision = 'c5058bc4988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tasks', 'limit_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'limit_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
