"""limit_atのデフォルトをNULL

Revision ID: bdcb9a453968
Revises: ead396e52b37
Create Date: 2021-08-08 21:39:22.031125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdcb9a453968'
down_revision = 'ead396e52b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
