"""Userテーブルにdelete_flgカラム追加

Revision ID: e497ecc26d17
Revises: 64de43dc85ad
Create Date: 2021-10-22 23:56:36.276346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e497ecc26d17'
down_revision = '64de43dc85ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_flg', sa.Boolean(), default=True, nullable=False))
    op.drop_index('username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'users', ['username'], unique=False)
    op.drop_column('users', 'delete_flg')
    # ### end Alembic commands ###
