"""[add] show, done column 

Revision ID: ead396e52b37
Revises: 720af62d9d7a
Create Date: 2021-07-25 13:21:54.066058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead396e52b37'
down_revision = '720af62d9d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_tasks', sa.Column('show', sa.Boolean(), nullable=False))
    op.add_column('sub_tasks', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('show', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'done')
    op.drop_column('tasks', 'show')
    op.drop_column('sub_tasks', 'done')
    op.drop_column('sub_tasks', 'show')
    # ### end Alembic commands ###
