"""limit_atのデフォルトをNULL

Revision ID: ee7a5a3b1c8e
Revises: bdcb9a453968
Create Date: 2021-08-08 21:40:31.645869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee7a5a3b1c8e'
down_revision = 'bdcb9a453968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_tasks', 'limit_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
